### ISSUE TITLE
Can't get to work due to java.lang.AssertionError

### ISSUE THREAD

**Issue by alekiv** [instaclustr/cassandra-sstable-tools#3]
Hi InstaClustr!

Trying to get work sstable-tools, but running into java.lang.AssertionError.
cassandra-sstable tools were built using  _ant -Dcassandra.version=3.0.11_ command

ic-summary
```
java.lang.AssertionError: []
        at org.apache.cassandra.db.lifecycle.Tracker.getMemtableFor(Tracker.java:312)
        at org.apache.cassandra.db.ColumnFamilyStore.apply(ColumnFamilyStore.java:1185)
        at org.apache.cassandra.db.Keyspace.applyInternal(Keyspace.java:573)
        at org.apache.cassandra.db.Keyspace.apply(Keyspace.java:421)
        at org.apache.cassandra.db.Mutation.apply(Mutation.java:210)
        at org.apache.cassandra.db.Mutation.apply(Mutation.java:215)
        at org.apache.cassandra.db.Mutation.apply(Mutation.java:224)
        at org.apache.cassandra.cql3.statements.ModificationStatement.executeInternalWithoutCondition(ModificationStatement.java:566)
        at org.apache.cassandra.cql3.statements.ModificationStatement.executeInternal(ModificationStatement.java:556)
        at org.apache.cassandra.cql3.QueryProcessor.executeInternal(QueryProcessor.java:295)
        at org.apache.cassandra.db.SystemKeyspace.updateSchemaVersion(SystemKeyspace.java:724)
        at org.apache.cassandra.config.Schema.updateVersion(Schema.java:563)
        at org.apache.cassandra.config.Schema.loadFromDisk(Schema.java:138)
        at org.apache.cassandra.config.Schema.loadFromDisk(Schema.java:126)
        at com.instaclustr.sstabletools.cassandra.CassandraBackend.<clinit>(CassandraBackend.java:33)
        at com.instaclustr.sstabletools.SummaryCollector.main(SummaryCollector.java:50)

```

**Comment by JoeCeramic** [comment]
The issue has been fixed by the latest commits
