### ISSUE TITLE
missing jamm-0.3.0.jar ?

### ISSUE THREAD

**Issue by tmcgrath** [instaclustr/cassandra-sstable-tools#4]
I have a feeling I'm missing something obvious, but whenever I run an ic-* command I'm getting an error about missing `jamm` jar similar to 

```
Error opening zip file or JAR manifest missing : /x/y/z/../lib/jamm-0.3.0.jar
Error occurred during initialization of VM
agent library failed to init: instrument
```

Here's what I've done so far:
git clone https://github.com/instaclustr/cassandra-sstable-tools.git
cd cassandra-sstable-tools
apt-get install ant
ant -Dcassandra.version=3.0.12  (built fine)
cp dist/3.0.12/ic-sstable-tools.jar /usr/share/cassandra/
restart cassandra
bin/ic-summary

I see a jamm jar 
cassandra-sstable-tools/cassandra/3.0.12/lib/jamm-0.3.0.jar

**Comment by tmcgrath** [comment]
Just an update

I've started to modify my `/usr/share/cassandra/cassandra.in.sh` which correct paths; one example

```# set JVM javaagent opts to avoid warnings/errors
if [ "$JVM_VENDOR" != "OpenJDK" -o "$JVM_VERSION" \> "1.6.0" ] \
      || [ "$JVM_VERSION" = "1.6.0" -a "$JVM_PATCH_VERSION" -ge 23 ]
then
    # JAVA_AGENT="$JAVA_AGENT -javaagent:$CASSANDRA_HOME/lib/jamm-0.3.0.jar"
    JAVA_AGENT="$JAVA_AGENT -javaagent:/usr/share/dse/cassandra/lib/jamm-0.3.0.jar"
fi
```

and guess I'll continue to do so.  Latest error

```sudo bin/ic-summary
java.lang.NoClassDefFoundError: org/apache/cassandra/config/Schema
	at com.instaclustr.sstabletools.cassandra.CassandraBackend.<clinit>(CassandraBackend.java:33)
	at com.instaclustr.sstabletools.SummaryCollector.main(SummaryCollector.java:50)
Caused by: java.lang.ClassNotFoundException: org.apache.cassandra.config.Schema
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more```

**Comment by vinayakmkmishra1792** [comment]
Did changing JAVA-AGENT solved your issue?
